### ISSUE TITLE
Embedded languages

### ISSUE THREAD

**Issue by pbrisbin** [restyled-io/restyled.io#109]
## Feature

It's common to see something like

```rb
# something.rb
def up
  <<-EOSQL
UPDATE x
  SET y = z
  WHERE q
EOSQL
end
```

It would be great if (assuming we had a SQL restyler) we could use it on the content in between known delimiters in files of other languages (in this case Ruby).

## Implementation Ideas

Add configuration syntax to the `Restyler` element

```yaml
restylers:
  - sql:
      include:
        - "*.sql"

     # new
     embedded:
       - include:
           - "*.rb"
         delimiters:
           - start: "<<-EOSQL"
             end: "^EOSQL"
```

- For any Restylers with `embedded`:
  - For any changed `include` paths:
    - If path contains `delimiters.start/end`:
      - Split the file at the delimiters
      - Place delimited content in new temporary files
      - Restyle those files using that Restyler
      - Splice updated content back into original file

*Assumption*: this is rare enough that we can naively do these gymnastics without feeling a huge performance hit. The upside is we can 100% re-use the embedded-language's existing Restyler as-is and the handling of embedded content is centralized in the restyle process (not any one Restyler).
