### ISSUE TITLE
Committed Config

### ISSUE THREAD

**Issue by pbrisbin** [restyled-io/restyled.io#16]
`.restyled.yaml`

```yaml
---
- foo
- bar
```

```yaml
- foo:
    arguments:
    - --baz
    - --bat
- bar
```

```yaml
restylers:
- command: foo
  arguments:
  - --bar
  # include, extensions, patterns, paths?
```
