### ISSUE TITLE
Request Review from "owner" breaks for Org repos

### ISSUE THREAD

**Issue by HurricanKai** [restyled-io/restyled.io#188]
See https://restyled.io/gh/SharpenedMinecraft/repos/SM3/jobs/191456
I closed https://github.com/SharpenedMinecraft/SM3/pull/58 and reopened it immediately.
It seems Restyled failed to create the PR?
Not sure if this isn't just Github Checks bugging out, the pipeline was duplicated too

**Comment by pbrisbin** [comment]
Thanks for the report, I think I see the bug. Let me talk it out to, so you can check my work...

The error Restyle hit was when requesting review on the Restyle PR. GitHub said,

> Reviews may only be requested from collaborators. One or more of the users or teams you specified is not a collaborator of the SharpenedMinecraft/SM3 repository.

What your `.restyled.yaml` (at the commit of this PR) shows is:

```yaml
request_review:
  origin: author
  forked: owner
```

This PR is a fork, so we'll be doing the "owner" logic. The intent would be to request review from the owner of the original PR (i.e. the person in charge of accepting outside contributions).

---

Unfortunately, this logic is naive and just looks at the PR's literal "owner", which is `SharpenedMinecraft`, which is not a user (it's an org), and (I assume) cannot be requested for review :bug: 

I'm actually not sure what's best here...

- Try to find Org collaborators and pick one by some heuristics
- Don't support review-request on forks at all
- Extend configuration to support specifying a specific user for fork review-requests

I welcome your thoughts on how this feature should work, if you have opinion.

---

In the meantime, I would suggest you adjust your config to one of the following:

```yaml
# Don't request reviews, this is the default if you just remove the key
request_review: none

# Request reviews from authors unless it's a fork
request_review:
  origin: author
  forked: none

# Request reviews from authors no matter what
#
# NOTE: I'm not sure if this one will work either, for similar reasons.
#
request_review: authors
```
