### ISSUE TITLE
Question about ".restyled.yaml"

### ISSUE THREAD

**Issue by drmingdrmer** [restyled-io/restyled.io#190]
If I added a ".restyled.yaml" into my repo with customized restylers, as following:

```
restylers:
    - name: prettier-markdown
      arguments:
          - "--print-width"
          - "80"
          - "--prose-wrap"
          - preserve        # here I made a change
    - name: rustfmt
      arguments:
          - "--edition"
          - "2018"          # here I made a change
```
My question is:
What is the exact behavior of merging customized argument with the default `restylers`?

The above settings seem to work correctly: it seems being merged recursively with the default. But I did not find a doc/wiki describing this behavior.

It'll be convenient for a user to have this information in this wiki page:
https://github.com/restyled-io/restyled.io/wiki/Configuration-Reference

**Comment by pbrisbin** [comment]
Hey there- thanks for reaching out!

> What is the exact behavior of merging customized argument with the default restylers?

[Valid keys](https://github.com/restyled-io/restyler/blob/a0970e2a97c3a13b4f9dcee941e7b6278d6921a2/config/default.yaml#L150-L189) are used directly from your configuration as-is when present. If you omit any values, they're pulled instead from the [Restyler Defaults](https://github.com/restyled-io/restyled.io/wiki/Available-Restylers).

> The above settings seem to work correctly: it seems being merged recursively with the default

I'm not totally sure what you mean by "merged recursively". To me, it's not quite that fancy. Any value you specify fully overrides the default value when that Restyler is run.

One possibly surprising thing (IMO), is that `command` and `arguments` are designed carefully to avoid your customizations breaking things. Specifically,

`command`, while intuitively *a* command (e.g. `prettier`), is technically an array. This is so that any arguments which are required for the tool to function as a Restyler (e.g. `--write`) can be specified there, and you are free to customize `arguments` without worrying about it.

So, as you might expect, the command for `prettier-markdown` is [`prettier --write`](https://github.com/restyled-io/restyled.io/wiki/Available-Restylers#prettier-markdown).

> It'll be convenient for a user to have this information in this wiki page

The situation could be improved, but the intent is to maintain this information only in the default config file in the source repository (linked above), as close as possible to the code. This file is linked to from that wiki page. Did you not notice the link, or do you find the in-YAML comments not clear enough?

**Comment by drmingdrmer** [comment]
Thank you for clarifying.

Actually, my question is:
If I have these in my `.restyled.yaml`:
```
restylers:
    - name: rustfmt
      arguments:
          - "--edition"
          - "2018"
```
And the default setting is:
```
---
enabled: true
name: rustfmt
image: restyled/restyler-rustfmt:v1.4.11-nightly
command:
  - rustfmt
arguments: []
include:
  - "**/*.rs"
interpreters: []
supports_arg_sep: true
supports_multiple_paths: true
```
I was not sure whether other keys will be extended automatically.
E.g.: do I have to include all other keys such as `supports_arg_sep` in my customization, like this:
```
restylers:
    - name: rustfmt
      arguments:
          - "--edition"
          - "2018"
      include:
          - "**/*.rs"
      interpreters: []
      ...
```

I now see that other keys will be kept the same as the default.

Thanks for this great tool. I do enjoy it. 😆😆
