### ISSUE TITLE
PR statuses

### ISSUE THREAD

**Issue by pbrisbin** [restyled-io/restyled.io#62]
- [x] Success

  I'd like to see a Green status on the PR if there were no style differences, so users know that Restyled did something and didn't just fail silently.

- [x] Failure

  I'm not sure about a failing status when there are differences, since we are adding a comment too. But perhaps for users who are familiar with Restyled, but don't yet want to turn on `auto`, a failing status where the *Details* link is to the Restyled PR could be a good UX.

- [x] Error

  It would be great to add a status when the Restyling process errors (this has most often been user-correctable, e.g. by ignoring a file with syntax a certain restyler chokes on), ~~but we have nowhere to link to yet to show the user the actual error, so maybe that's a pre-requisite -- or maybe we link to a general help page on the wiki.~~

- [x] Configurability

  All of this should be disable-able via config:

  ```yaml
  # key names TBD
  statuses:
    success: true|false
    differences: true|false
    error: true|false

  # and sugar to apply to all
  statuses: true|false
  ```
