### ISSUE TITLE
Config file doesn't seem to be picked up

### ISSUE THREAD

**Issue by joneshf** [restyled-io/restyled.io#85]
I have a repo with some Haskell code in the `lib` directory. With no config, restyled doesn't pick up changes to this code; it will still check the rest of the repo, though. If I add a configuration file, restyled doesn't check anything in the repo.

I've tried with a small file:
```YAML
---
- stylish-haskell:
    include:
      - '**/*.hs'
```

And with a more fleshed out file:
```YAML
---
auto: false
enabled: true
remote_files: []
restylers:
  - stylish-haskell:
      include:
        - '**/*.hs'
statuses: true
```

The PR in question: https://github.com/joneshf/purcel/pull/13

Any ideas what might be happening? Maybe I messed up the format, or the file name or something?
